import preprocess.searchHiddenSize
import preprocess.searchM1number
import preprocess.sortM1neurons

searchHiddenSize = preprocess.searchHiddenSize.searchHiddenSize
searchM1number = preprocess.searchM1number.searchM1number
sortM1neurons = preprocess.sortM1neurons.sortM1neurons