function [ymax, ymin, h] = get_yl(plot_lR,plot_hR,plot_lRp,plot_hRp,plot_lRsp,plot_hRsp,neuronIdx)
ymax = max(max([plot_lR(neuronIdx,:);plot_hR(neuronIdx,:); ...
                plot_lRp(neuronIdx,:);plot_hRp(neuronIdx,:); ...
                plot_lRsp(neuronIdx,:);plot_hRsp(neuronIdx,:)]));
ymax = ceil(10*ymax)/10;
ymin = min(min([plot_lR(neuronIdx,:);plot_hR(neuronIdx,:); ...
                plot_lRp(neuronIdx,:);plot_hRp(neuronIdx,:); ...
                plot_lRsp(neuronIdx,:);plot_hRsp(neuronIdx,:)]));
ymin = floor(10*ymin)/10;
h = ymax;
end
